# Generated by Django 3.0.8 on 2020-07-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Report_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_1_name', models.CharField(max_length=100, unique=True, verbose_name='Main Report Group')),
                ('rg_1_name_cd', models.DateField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='USALI_Report_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_3_name', models.CharField(max_length=100, unique=True, verbose_name='USALI Report Group')),
                ('rg_3_name_cd', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('rg_1_grp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Main_Report_Group', verbose_name='Main Report Group')),
            ],
        ),
        migrations.CreateModel(
            name='Rixos_Report_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_2_name', models.CharField(max_length=100, unique=True, verbose_name='PL Report Group')),
                ('rg_2_name_cd', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('rg_1_grp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Main_Report_Group', verbose_name='Main Report Group')),
            ],
        ),
        migrations.CreateModel(
            name='Account_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_code', models.CharField(max_length=20, unique=True, verbose_name='Account Code')),
                ('acc_name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('acc_cd', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('rg_1', models.ManyToManyField(to='app_1.Rixos_Report_Group')),
                ('rg_2', models.ManyToManyField(to='app_1.USALI_Report_Group')),
            ],
        ),
    ]
